dist: trusty

language:
  - cpp

before_install:
 - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update -qq
 - sudo apt-get install qtbase5-dev qtdeclarative5-dev qtquickcontrols2-5-dev qtmultimedia5-dev
 - sudo apt-get install qt5-default qttools5-dev-tools

script:
  - qmake
  - make

notifications:
  email: false