dist: bionic

language:
  - cpp

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -y qtbase5-dev qtdeclarative5-dev qtquickcontrols2-5-dev qtmultimedia5-dev
 - sudo apt-get install -y qt5-default qttools5-dev-tools
 - sudo apt-get install -y libgtest-dev cmake
 - sudo wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz
 - sudo tar xf release-1.7.0.tar.gz
 - cd googletest-release-1.7.0
 - sudo cmake -DBUILD_SHARED_LIBS=ON .
 - sudo make
 - sudo cp -a include/gtest /usr/include
 - sudo cp -a libgtest_main.so libgtest.so /usr/lib/
 - cd ..

script:
  - qmake
  - make
  - ls
  - ls ./app
  - ls ./tests
  - ./tests/run-tests

notifications:
  email: false