dist: bionic

language:
  - cpp

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -y qtbase5-dev qtdeclarative5-dev qtquickcontrols2-5-dev qtmultimedia5-dev
 - sudo apt-get install -y qt5-default qttools5-dev-tools
 - pip install --user cpp-coveralls

addons:
  sonarcloud:
    organization: "nikonp"
    token: $SONAR_TOKEN

script:
  - qmake
  - make
  - ./tests/run-tests
  - ./configure --enable-gcov && make && make check

after_success:
  - coveralls --exclude external --exclude tests --gcov-options '\-lp'
#  - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
#  - sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output

notifications:
  email: false
  