dist: bionic

language:
  - cpp

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -y qtbase5-dev qtdeclarative5-dev qtquickcontrols2-5-dev qtmultimedia5-dev
 - sudo apt-get install -y qt5-default qttools5-dev-tools
 - sudo apt-get install -y libgtest-dev libgmock-dev

script:
  - qmake
  - make
  - ls
  - ls ./app
  - ls ./tests
  - ./tests/tests

notifications:
  email: false